etcd kv service
pavelbezpravel/ydb pull request #2
Opened 2024-03-12 08:30 UTC by pavelbezpravel

### Changelog entry

introduce etcd KV grpc service

### Changelog category 

* Experimental feature

### Additional information

...

2024-04-04 16:08 UTC, dorooleg commented on ydb/services/etcd/api/etcdserverpb/kv/grpc_service.cpp
> +    // ADD_REQUEST(Put, PutRequest, PutResponse, DoPut);
Давай остальные ручки расскоментим

2024-04-06 06:00 UTC, pavelbezpravel commented on ydb/services/etcd/api/etcdserverpb/kv/grpc_service.cpp
> +    // ADD_REQUEST(Put, PutRequest, PutResponse, DoPut);
fix

2024-04-06 06:01 UTC, pavelbezpravel commented
@dorooleg @APozdniakov lgtm?

2024-04-06 08:49 UTC, dorooleg requested changes

2024-04-06 08:49 UTC, dorooleg commented on ydb/core/base/events.h
> +        ES_ETCD_REVISION,
А зачем тут ES_ETCD_REVISION ?

2024-04-06 08:49 UTC, dorooleg commented on ydb/core/driver_lib/run/run.cpp
> +            // TODO [pavelbezpravel]: add pther etcd services later.
а что такое pther?

2024-04-06 08:49 UTC, dorooleg commented on ydb/core/grpc_services/etcd/api/kv/rpc_txn.cpp
> +    f.RegisterActor(new TTxnRequestRPC(req));
Везде можно было бы сделать один актор который умеет несколько handler обрабатывать, а уже реализация будет в Акторах Леши. Иначе много дублирущего кода получается

2024-04-06 08:49 UTC, dorooleg commented on ydb/services/etcd/api/kv/grpc_service.cpp
> +    // TODO [pavelbezpravel]: WIP.
Это todo нужно? Выглядит что основное уже добавил для старта

2024-04-06 11:35 UTC, APozdniakov commented on ydb/core/base/events.h
> +        ES_ETCD_REVISION,
работа с ревизиями вынесена в отдельную библиотеку, потому что ревизии еще есть в Lease и Watch API. Думаешь, все сообщения сделать с тегом `ES_ETCD`?

2024-04-06 19:00 UTC, pavelbezpravel commented on ydb/core/driver_lib/run/run.cpp
> +            // TODO [pavelbezpravel]: add pther etcd services later.
очепятка: *other*. Это просто отметка на будущее, чтоб другие сервисы добавить здесь же

2024-04-06 19:05 UTC, pavelbezpravel commented on ydb/services/etcd/api/kv/grpc_service.cpp
> +    // TODO [pavelbezpravel]: WIP.
Забыл удалить

2024-04-07 17:09 UTC, pavelbezpravel commented on ydb/core/grpc_services/etcd/api/kv/rpc_txn.cpp
> +    f.RegisterActor(new TTxnRequestRPC(req));
Думаю, что сделал получше :)

2024-04-07 17:11 UTC, pavelbezpravel commented on ydb/core/base/events.h
> +        ES_ETCD_REVISION,
@dorooleg, как лучше сделать? Откатываем к `ES_ETCD` или оставляем как сейчас?

2024-04-08 06:57 UTC, merged